// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlIN2-Gc9GsiVv6vKpXtOhXSna8VGqu0U',
    appId: '1:776463127758:web:c2d17186d35d477194ec9f',
    messagingSenderId: '776463127758',
    projectId: 'to-do-apps-82768',
    authDomain: 'to-do-apps-82768.firebaseapp.com',
    storageBucket: 'to-do-apps-82768.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD04QsnRFTD_Zre7xSHe60z5ODRT_GhtpM',
    appId: '1:776463127758:android:24983a2fa5ba545d94ec9f',
    messagingSenderId: '776463127758',
    projectId: 'to-do-apps-82768',
    storageBucket: 'to-do-apps-82768.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgFBDvjP6NMwlQz3sXzHbrPiFQ1Mbdiew',
    appId: '1:776463127758:ios:d4781187181fdcf494ec9f',
    messagingSenderId: '776463127758',
    projectId: 'to-do-apps-82768',
    storageBucket: 'to-do-apps-82768.firebasestorage.app',
    iosBundleId: 'com.example.projectToDoApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgFBDvjP6NMwlQz3sXzHbrPiFQ1Mbdiew',
    appId: '1:776463127758:ios:d4781187181fdcf494ec9f',
    messagingSenderId: '776463127758',
    projectId: 'to-do-apps-82768',
    storageBucket: 'to-do-apps-82768.firebasestorage.app',
    iosBundleId: 'com.example.projectToDoApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlIN2-Gc9GsiVv6vKpXtOhXSna8VGqu0U',
    appId: '1:776463127758:web:2ba5e3158e88860294ec9f',
    messagingSenderId: '776463127758',
    projectId: 'to-do-apps-82768',
    authDomain: 'to-do-apps-82768.firebaseapp.com',
    storageBucket: 'to-do-apps-82768.firebasestorage.app',
  );
}
